/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo_2024;

import java.util.HashMap;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JButton;
import javax.swing.ImageIcon;
import java.awt.BorderLayout;
/**
 *
 * @author andre
 */
public class Huvudmeny extends javax.swing.JFrame {
    
    private InfDB idb;
    private String admins;
    private String projl;
    private String anvandare;
    private String queryAid;
    private AnstalldMeny anstalld;

    /**
     * Creates new form Huvudmeny
     */
    public Huvudmeny(InfDB idb, String queryAid, String admins, String projl) {
        initComponents();
        setLocationRelativeTo(null); //Den här koden sätter fönstret i mitten av skärmen. 
        this.idb = idb;
        this.admins = admins;
        this.queryAid = queryAid;
        this.projl = projl;
        this.anvandare = queryAid;
        kontrolleraBehorigheter();
        this.anstalld = new AnstalldMeny(idb);
        visaAnvandaresNamnOchEpost(queryAid);
        this.setTitle("NGO-matic");

    }
private void kontrolleraBehorigheter() {
    try {
        
        String projektledareQuery = "SELECT COUNT(*) FROM projekt WHERE projektchef = '" + queryAid + "'";
        int antalProjekt = Integer.parseInt(idb.fetchSingle(projektledareQuery));

        if (antalProjekt > 0) {
            menyProjektledning.setVisible(true);
        } else {
            menyProjektledning.setVisible(false);
        }

        
        String adminQuery = "SELECT behorighetsniva FROM admin WHERE aid = '" + queryAid + "'";
        String behorighetsniva = idb.fetchSingle(adminQuery);

        if (behorighetsniva != null && behorighetsniva.equals("1")) {
            menyAdministration.setVisible(true);
        } else {
            menyAdministration.setVisible(false);
        }

    } catch (InfException e) {
        System.out.println("Ett fel inträffade vid kontroll av behörigheter: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        lblNamn = new javax.swing.JLabel();
        lblEpost = new javax.swing.JLabel();
        lblRoll = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menyMinaUppgifter = new javax.swing.JMenu();
        mvminMinaUppgifter = new javax.swing.JMenuItem();
        mvminLoggaUt = new javax.swing.JMenuItem();
        menyProjekt = new javax.swing.JMenu();
        mvprojMinaProjekt = new javax.swing.JMenuItem();
        mvprojAllaProjekt = new javax.swing.JMenuItem();
        mvprojProjektPartners = new javax.swing.JMenuItem();
        mvprojHallarbhetsmal = new javax.swing.JMenuItem();
        menyPersonal = new javax.swing.JMenu();
        mvpersPersonalPaMinAvdelning = new javax.swing.JMenuItem();
        mvpersHandlaggare = new javax.swing.JMenuItem();
        menyProjektledning = new javax.swing.JMenu();
        mvproledMinaProjekt = new javax.swing.JMenuItem();
        mvproledAndraPartnersForProjekt = new javax.swing.JMenuItem();
        mvproledStatistik = new javax.swing.JMenuItem();
        menyAdministration = new javax.swing.JMenu();
        mvadnPersonal = new javax.swing.JMenuItem();
        mvadnAvdelningar = new javax.swing.JMenuItem();
        mvadnProjekt = new javax.swing.JMenuItem();
        mvadnPartners = new javax.swing.JMenuItem();
        mvproledAndraPartnersForProjekt1 = new javax.swing.JMenuItem();
        mvadnHallbarhetsmal = new javax.swing.JMenuItem();
        mvadnLand = new javax.swing.JMenuItem();
        menyHjalp = new javax.swing.JMenu();
        mvhjOm = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu7.setText("jMenu7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblNamn.setText("Inloggad användare");

        lblEpost.setText("inloggadAnvändare");

        lblRoll.setText("Administratör");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNamn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                        .addComponent(lblRoll))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblEpost)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamn)
                    .addComponent(lblRoll))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEpost)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menyMinaUppgifter.setText("Mina uppgifter");

        mvminMinaUppgifter.setText("Mina uppgifter");
        mvminMinaUppgifter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mvminMinaUppgifterActionPerformed(evt);
            }
        });
        menyMinaUppgifter.add(mvminMinaUppgifter);

        mvminLoggaUt.setText("Logga ut");
        mvminLoggaUt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mvminLoggaUtActionPerformed(evt);
            }
        });
        menyMinaUppgifter.add(mvminLoggaUt);

        jMenuBar1.add(menyMinaUppgifter);

        menyProjekt.setText("Projekt");

        mvprojMinaProjekt.setText("Mitt deltagande");
        mvprojMinaProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mvprojMinaProjektActionPerformed(evt);
            }
        });
        menyProjekt.add(mvprojMinaProjekt);

        mvprojAllaProjekt.setText("Avdelningens projekt");
        mvprojAllaProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mvprojAllaProjektActionPerformed(evt);
            }
        });
        menyProjekt.add(mvprojAllaProjekt);

        mvprojProjektPartners.setText("Projektpartners");
        mvprojProjektPartners.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mvprojProjektPartnersActionPerformed(evt);
            }
        });
        menyProjekt.add(mvprojProjektPartners);

        mvprojHallarbhetsmal.setText("Hållbarhetsmål");
        mvprojHallarbhetsmal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mvprojHallarbhetsmalActionPerformed(evt);
            }
        });
        menyProjekt.add(mvprojHallarbhetsmal);

        jMenuBar1.add(menyProjekt);

        menyPersonal.setText("Personal");

        mvpersPersonalPaMinAvdelning.setText("Personal på min avdelning");
        mvpersPersonalPaMinAvdelning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mvpersPersonalPaMinAvdelningActionPerformed(evt);
            }
        });
        menyPersonal.add(mvpersPersonalPaMinAvdelning);

        mvpersHandlaggare.setText("Handläggare");
        menyPersonal.add(mvpersHandlaggare);

        jMenuBar1.add(menyPersonal);

        menyProjektledning.setText("Projektledning");

        mvproledMinaProjekt.setText("Mina projekt");
        mvproledMinaProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mvproledMinaProjektActionPerformed(evt);
            }
        });
        menyProjektledning.add(mvproledMinaProjekt);

        mvproledAndraPartnersForProjekt.setText("Ändra partners för projekt");
        mvproledAndraPartnersForProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mvproledAndraPartnersForProjektActionPerformed(evt);
            }
        });
        menyProjektledning.add(mvproledAndraPartnersForProjekt);

        mvproledStatistik.setText("Statistik");
        mvproledStatistik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mvproledStatistikActionPerformed(evt);
            }
        });
        menyProjektledning.add(mvproledStatistik);

        jMenuBar1.add(menyProjektledning);

        menyAdministration.setText("Administration");
        menyAdministration.setToolTipText("");

        mvadnPersonal.setText("Personal");
        mvadnPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mvadnPersonalActionPerformed(evt);
            }
        });
        menyAdministration.add(mvadnPersonal);

        mvadnAvdelningar.setText("Avdelningar");
        mvadnAvdelningar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mvadnAvdelningarActionPerformed(evt);
            }
        });
        menyAdministration.add(mvadnAvdelningar);

        mvadnProjekt.setText("Projekt");
        mvadnProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mvadnProjektActionPerformed(evt);
            }
        });
        menyAdministration.add(mvadnProjekt);

        mvadnPartners.setText("Partners");
        mvadnPartners.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mvadnPartnersActionPerformed(evt);
            }
        });
        menyAdministration.add(mvadnPartners);

        mvproledAndraPartnersForProjekt1.setText("Ändra partners för projekt");
        mvproledAndraPartnersForProjekt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mvproledAndraPartnersForProjekt1ActionPerformed(evt);
            }
        });
        menyAdministration.add(mvproledAndraPartnersForProjekt1);

        mvadnHallbarhetsmal.setText("Hållbarhetsmål");
        mvadnHallbarhetsmal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mvadnHallbarhetsmalActionPerformed(evt);
            }
        });
        menyAdministration.add(mvadnHallbarhetsmal);

        mvadnLand.setText("Land");
        mvadnLand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mvadnLandActionPerformed(evt);
            }
        });
        menyAdministration.add(mvadnLand);

        jMenuBar1.add(menyAdministration);

        menyHjalp.setText("Hjälp");
        menyHjalp.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        mvhjOm.setText("Om");
        mvhjOm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mvhjOmActionPerformed(evt);
            }
        });
        menyHjalp.add(mvhjOm);

        jMenuBar1.add(menyHjalp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(237, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(409, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void visaAnvandaresNamnOchEpost(String queryAid)
    {
        String roll = ((admins == null) ? "Handläggare" : "Administratör"); //Korthands-if
        HashMap<String, String> resultat = anstalld.hamtaAnstalldsData(queryAid);
        lblNamn.setText(resultat.get("fornamn") + " " + resultat.get("efternamn"));
        lblEpost.setText(resultat.get("epost"));
        lblRoll.setText(roll);
    }
    
    /**
     * Knappar följer nedan
     */
    
    private void mvminLoggaUtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mvminLoggaUtActionPerformed
        new InloggningMeny(idb).setVisible (true);
        this.setVisible(false);
    }//GEN-LAST:event_mvminLoggaUtActionPerformed

    private void mvadnPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mvadnPersonalActionPerformed
        new AnstalldMeny(idb, admins, anvandare).setVisible(true);
    }//GEN-LAST:event_mvadnPersonalActionPerformed

    private void mvhjOmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mvhjOmActionPerformed
    
    JFrame omRuta = new JFrame("Om NGO-matic");
    omRuta.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    omRuta.setSize(500, 400); 
    omRuta.setLayout(new BorderLayout());
    omRuta.setLocationRelativeTo(null); 

    JLabel titelLabel = new JLabel("<html><h1 style='color:blue; text-align:center;'>NGO-matic</h1></html>", JLabel.CENTER);

    String infoText = "<html>"
            + "<p style='text-align:center;'>Ett program utvecklat för <b>SDG Sweden</b><br> som en del av kursen <i>IK100G Informatik 30hp</i> <br>delkursen <b>Systemutvecklingsprojekt</b>.</p>"
            + "<br>"
            + "<h3 style='text-align:center;'>Utvecklat av:</h3>"
            + "<ul>"
            + "<li style='text-align:left;'>Andreas Galistel</li>"
            + "<li style='text-align:left;'>Claudia Kourieh</li>"
            + "<li style='text-align:left;'>Fredrik Magnusson</li>"
            + "<li style='text-align:left;'>Märta Sjöblom</li>"
            + "</ul>"
            + "<br>"
            + "<p style='text-align:center;'>NGO-matic är designat för att hjälpa <b>SDG Sweden</b><br>som arbetar med tekniska lösningar för utvecklingsländer.</p>"
            + "</html>";
    
    JLabel infoLabel = new JLabel(infoText, JLabel.CENTER);
    JButton stangKnapp = new JButton("Stäng");
    stangKnapp.addActionListener(e -> omRuta.dispose());
    omRuta.add(titelLabel, BorderLayout.NORTH);
    omRuta.add(infoLabel, BorderLayout.CENTER);
    omRuta.add(stangKnapp, BorderLayout.SOUTH);
    omRuta.setVisible(true);
    }//GEN-LAST:event_mvhjOmActionPerformed

    private void mvminMinaUppgifterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mvminMinaUppgifterActionPerformed
        new EditAnstalld(idb, queryAid, admins, anvandare).setVisible(true);
    }//GEN-LAST:event_mvminMinaUppgifterActionPerformed

    private void mvadnAvdelningarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mvadnAvdelningarActionPerformed
        new AvdelningMeny(idb).setVisible(true);
    }//GEN-LAST:event_mvadnAvdelningarActionPerformed

    private void mvadnProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mvadnProjektActionPerformed
        new ProjektMeny(idb).setVisible(true);
    }//GEN-LAST:event_mvadnProjektActionPerformed

    private void mvprojMinaProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mvprojMinaProjektActionPerformed
        new ProjektMeny(idb, queryAid).setVisible(true);
    }//GEN-LAST:event_mvprojMinaProjektActionPerformed

    private void mvproledMinaProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mvproledMinaProjektActionPerformed
        new ProjektMeny(idb, queryAid, true).setVisible(true);
    }//GEN-LAST:event_mvproledMinaProjektActionPerformed

    private void mvprojAllaProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mvprojAllaProjektActionPerformed
        new ProjektMeny(idb, true, queryAid).setVisible(true);
    }//GEN-LAST:event_mvprojAllaProjektActionPerformed

    private void mvadnHallbarhetsmalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mvadnHallbarhetsmalActionPerformed
        new HallbarhetsmalMeny(idb, false).setVisible(true);
    }//GEN-LAST:event_mvadnHallbarhetsmalActionPerformed

    private void mvadnLandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mvadnLandActionPerformed
        new LandMeny(idb).setVisible(true);
    }//GEN-LAST:event_mvadnLandActionPerformed

    private void mvpersPersonalPaMinAvdelningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mvpersPersonalPaMinAvdelningActionPerformed
      new AnstalldMeny(idb, anvandare).setVisible(true);
    }//GEN-LAST:event_mvpersPersonalPaMinAvdelningActionPerformed

    private void mvadnPartnersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mvadnPartnersActionPerformed
        new PartnerMeny(idb).setVisible(true);
    }//GEN-LAST:event_mvadnPartnersActionPerformed

    private void mvproledStatistikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mvproledStatistikActionPerformed
        new Statistik(idb, queryAid).setVisible(true);
    }//GEN-LAST:event_mvproledStatistikActionPerformed

    private void mvprojHallarbhetsmalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mvprojHallarbhetsmalActionPerformed
        new HallbarhetsmalMeny(idb, true).setVisible(true);
    }//GEN-LAST:event_mvprojHallarbhetsmalActionPerformed

    private void mvprojProjektPartnersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mvprojProjektPartnersActionPerformed
        new PartnerMeny(idb, queryAid).setVisible(true);
    }//GEN-LAST:event_mvprojProjektPartnersActionPerformed

    private void mvproledAndraPartnersForProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mvproledAndraPartnersForProjektActionPerformed
        new EditProjektPartner(idb, queryAid).setVisible(true);
    }//GEN-LAST:event_mvproledAndraPartnersForProjektActionPerformed

    private void mvproledAndraPartnersForProjekt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mvproledAndraPartnersForProjekt1ActionPerformed
        new EditProjektPartner(idb).setVisible(true);
    }//GEN-LAST:event_mvproledAndraPartnersForProjekt1ActionPerformed




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEpost;
    private javax.swing.JLabel lblNamn;
    private javax.swing.JLabel lblRoll;
    private javax.swing.JMenu menyAdministration;
    private javax.swing.JMenu menyHjalp;
    private javax.swing.JMenu menyMinaUppgifter;
    private javax.swing.JMenu menyPersonal;
    private javax.swing.JMenu menyProjekt;
    private javax.swing.JMenu menyProjektledning;
    private javax.swing.JMenuItem mvadnAvdelningar;
    private javax.swing.JMenuItem mvadnHallbarhetsmal;
    private javax.swing.JMenuItem mvadnLand;
    private javax.swing.JMenuItem mvadnPartners;
    private javax.swing.JMenuItem mvadnPersonal;
    private javax.swing.JMenuItem mvadnProjekt;
    private javax.swing.JMenuItem mvhjOm;
    private javax.swing.JMenuItem mvminLoggaUt;
    private javax.swing.JMenuItem mvminMinaUppgifter;
    private javax.swing.JMenuItem mvpersHandlaggare;
    private javax.swing.JMenuItem mvpersPersonalPaMinAvdelning;
    private javax.swing.JMenuItem mvprojAllaProjekt;
    private javax.swing.JMenuItem mvprojHallarbhetsmal;
    private javax.swing.JMenuItem mvprojMinaProjekt;
    private javax.swing.JMenuItem mvprojProjektPartners;
    private javax.swing.JMenuItem mvproledAndraPartnersForProjekt;
    private javax.swing.JMenuItem mvproledAndraPartnersForProjekt1;
    private javax.swing.JMenuItem mvproledMinaProjekt;
    private javax.swing.JMenuItem mvproledStatistik;
    // End of variables declaration//GEN-END:variables
}
