package ngo_2024;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author Claudia Kourieh
 */
public class StadMeny extends javax.swing.JFrame {

    private InfDB idb;
    private LandMeny land;

    public StadMeny(InfDB idb) {
        this.idb = idb;
        this.land = new LandMeny(idb);
        initComponents();
        setLocationRelativeTo(null); // Centrera fönstret
        pupuleraStadTabell(getAllaStader()); // Ladda alla städer direkt vid start
    }

    /**
     * Hämtar och visar alla städer i tabellen.
     */
    private void pupuleraStadTabell(ArrayList<HashMap<String, String>> allaStader) {
        if (allaStader != null) {
            DefaultTableModel tableModel = new DefaultTableModel();
            tableModel.setRowCount(0);

            tableModel.addColumn("ID");
            tableModel.addColumn("Namn");
            tableModel.addColumn("Land");

            for (HashMap<String, String> rad : allaStader) {
                String landId = rad.get("land");
                String landNamn = land.getLandNamnFranId(landId); // Hämtar landets namn baserat på ID

                tableModel.addRow(new Object[]{
                    rad.get("sid"),
                    rad.get("namn"),
                    landNamn
                });
            }
            jTable1.setModel(tableModel);
        } else {
            JOptionPane.showMessageDialog(this, "Inga städer hittades.");
        }
    }

    /**
     * Hämtar ut namn för en stad.
     * @param sid
     * @return 
     */
    public String getNamn(int sid)
        {
            String namn;
            try
            {
                String query = "SELECT namn FROM stad WHERE sid = " + sid;
                namn = idb.fetchSingle(query);
            }
            catch(InfException e)
            {
                JOptionPane.showMessageDialog(this, "Ingen stad hittades.");
                namn = null;
            }
        return namn;
    }
    
    public ArrayList<HashMap<String, String>> getAllaStader()
    {
        ArrayList<HashMap<String, String>> allaStäder;
        try
        {
            String sqlfråga = "SELECT * FROM stad";
            allaStäder = idb.fetchRows(sqlfråga);
        }
        catch(InfException e)
        {
            JOptionPane.showMessageDialog(this, "Kunde inte hämta data om städer ur databasen.");
            allaStäder = null;
        }
        return allaStäder;
    }
        
    /**
     * Raderar den valda staden.
     */
    private void raderaStad() {
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow != -1) {
            Object stadId = jTable1.getValueAt(selectedRow, 0); // Hämtar stadens ID

            try {
                String query = "DELETE FROM stad WHERE sid = " + stadId;
                idb.delete(query);
                JOptionPane.showMessageDialog(this, "Staden har raderats!");
                pupuleraStadTabell(getAllaStader()); // Uppdatera tabellen
            } catch (InfException e) {
                JOptionPane.showMessageDialog(this, "Det gick inte att radera staden. Kontrollera att databasen fungerar som den ska");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Välj en stad att radera!");
        }
    }

    /**
     * Öppnar upp EditLand för markerat land.
     */
    private void editStad() {
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow != -1) {
            String stad = jTable1.getValueAt(selectedRow, 0).toString();
            new EditStad(idb, stad).setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Ingen rad är markerad");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUppdatera = new javax.swing.JButton();
        btnÄndra = new javax.swing.JButton();
        btnRadera = new javax.swing.JButton();
        btnNyStad = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Stad");

        btnUppdatera.setText("Uppdatera");
        btnUppdatera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUppdateraActionPerformed(evt);
            }
        });

        btnÄndra.setText("Ändra");
        btnÄndra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnÄndraActionPerformed(evt);
            }
        });

        btnRadera.setText("Radera");
        btnRadera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaderaActionPerformed(evt);
            }
        });

        btnNyStad.setText("Ny Stad");
        btnNyStad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNyStadActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Namn", "Land"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnUppdatera)
                        .addGap(18, 18, 18)
                        .addComponent(btnÄndra)
                        .addGap(18, 18, 18)
                        .addComponent(btnRadera)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNyStad)))
                .addGap(0, 159, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUppdatera)
                    .addComponent(btnÄndra)
                    .addComponent(btnRadera)
                    .addComponent(btnNyStad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUppdateraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUppdateraActionPerformed
        pupuleraStadTabell(getAllaStader());
    }//GEN-LAST:event_btnUppdateraActionPerformed

    private void btnÄndraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnÄndraActionPerformed
        editStad();
    }//GEN-LAST:event_btnÄndraActionPerformed

    private void btnRaderaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaderaActionPerformed
        raderaStad();
    }//GEN-LAST:event_btnRaderaActionPerformed

    private void btnNyStadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNyStadActionPerformed
        new EditStad(idb, null).setVisible(true);
    }//GEN-LAST:event_btnNyStadActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNyStad;
    private javax.swing.JButton btnRadera;
    private javax.swing.JButton btnUppdatera;
    private javax.swing.JButton btnÄndra;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
