/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo_2024;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author Märta Sjöblom
 */
public class Statistik extends javax.swing.JFrame {
    
    private InfDB idb;
    private String aid;
    /**
     * Creates new form Statistik
     */
    public Statistik(InfDB idb, String aid) {
        this.idb = idb;
        this.aid = aid;
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE );
        setMinaKostnader();
        setAvdelningsKostnader();
        setTotalaKostnader();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTotalKostnadMina = new javax.swing.JLabel();
        txtTotalKostnadMina = new javax.swing.JTextField();
        lblPagaende = new javax.swing.JLabel();
        txtPagaende = new javax.swing.JTextField();
        lblAvslutade = new javax.swing.JLabel();
        txtAvslutade = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblTotalKostnadAlla = new javax.swing.JLabel();
        txtTotalKostnadAlla = new javax.swing.JTextField();
        lblStatistikRubrik = new javax.swing.JLabel();
        lblTotalKostnadAvd = new javax.swing.JLabel();
        txtTotalKostnadAvd = new javax.swing.JTextField();
        lblRubrik2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTotalKostnadMina.setText("Total kostnad");

        lblPagaende.setText("- varav pågående");

        lblAvslutade.setText("- varav avslutade");

        lblTotalKostnadAlla.setText("Kostnad totalt");

        lblStatistikRubrik.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblStatistikRubrik.setText("Statistik");

        lblTotalKostnadAvd.setText("Kostnad - Min avdelning");

        lblRubrik2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRubrik2.setText("Som projektledare");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblRubrik2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblPagaende, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAvslutade, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTotalKostnadMina, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblStatistikRubrik, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTotalKostnadMina, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                    .addComponent(txtPagaende, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtAvslutade, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTotalKostnadAvd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTotalKostnadAvd, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTotalKostnadAlla)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTotalKostnadAlla, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(116, 116, 116))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(31, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStatistikRubrik)
                .addGap(10, 10, 10)
                .addComponent(lblRubrik2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalKostnadMina)
                    .addComponent(txtTotalKostnadMina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPagaende)
                    .addComponent(txtPagaende, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAvslutade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvslutade))
                .addGap(37, 37, 37)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotalKostnadAvd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(lblTotalKostnadAlla))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txtTotalKostnadAvd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTotalKostnadAlla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Räknar ut kostnaden för inloggad användare, och delar upp på pågående och
     * avslutade projekt
     */
    private void setMinaKostnader() {
        double minKostnad = 0;
        double pågåendeSumma = 0;
        double avslutadeSumma = 0;
        try {
            ArrayList<HashMap<String, String>> minaProjekt = new ArrayList<>();
            try {
                String sqlfråga = "SELECT * FROM projekt where projektchef =" + aid;
                minaProjekt = idb.fetchRows(sqlfråga);
            } catch (InfException e) {
                System.out.println("Kunde inte hämta projekt.\n" + e.getMessage());
                JOptionPane.showMessageDialog(null, "Kunde inte hämta projekt.");
            }
            for (HashMap<String, String> ettProjekt : minaProjekt) {
                minKostnad += Double.parseDouble(ettProjekt.get("kostnad"));
                String status = ettProjekt.get("status");
                if (status.equals("Pågående")) {
                    pågåendeSumma += Double.parseDouble(ettProjekt.get("kostnad"));
                } else if (status.equals("Avslutat")) {
                    avslutadeSumma += Double.parseDouble(ettProjekt.get("kostnad"));
                }
            }
        } catch (Exception ex) {
            System.out.println("Inga projekt på denna person" + ex.getMessage());
        }
        txtTotalKostnadMina.setText("" + minKostnad);
        txtPagaende.setText("" + pågåendeSumma);
        txtAvslutade.setText("" + avslutadeSumma);
    }
    
    /**
     * Räknar ut kostnader för avdelningen som inloggad person jobbar vid
     */
    private void setAvdelningsKostnader(){
        double avdSumma = 0;
        String sqlAvdKost = "select kostnad from projekt where pid in (select pid from ans_proj where aid in (select aid from anstalld where avdelning = (select avdelning from anstalld where aid = "+aid+")));";
        ArrayList<String> avdKostnader = new ArrayList<>();
        try {
            avdKostnader = idb.fetchColumn(sqlAvdKost);
        }
        catch (InfException e) {
            System.out.println(e.getMessage());
        }
        for (String enKostnad : avdKostnader) {
            avdSumma += Double.parseDouble(enKostnad);
        }
        txtTotalKostnadAvd.setText(""+avdSumma);
    }
    
    /**
     * Räknar ut kostnaden för alla projekt i systemet
     */
    private void setTotalaKostnader(){
        double totSumma = 0;
        String sqlTotKost = "select kostnad from projekt;";
        ArrayList<String> totKostnader = new ArrayList<>();
        try {
            totKostnader = idb.fetchColumn(sqlTotKost);
        }
        catch (InfException e) {
            System.out.println(e.getMessage());
        }
        for (String enKostnad : totKostnader) {
            totSumma += Double.parseDouble(enKostnad);
        }
        txtTotalKostnadAlla.setText(""+totSumma);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAvslutade;
    private javax.swing.JLabel lblPagaende;
    private javax.swing.JLabel lblRubrik2;
    private javax.swing.JLabel lblStatistikRubrik;
    private javax.swing.JLabel lblTotalKostnadAlla;
    private javax.swing.JLabel lblTotalKostnadAvd;
    private javax.swing.JLabel lblTotalKostnadMina;
    private javax.swing.JTextField txtAvslutade;
    private javax.swing.JTextField txtPagaende;
    private javax.swing.JTextField txtTotalKostnadAlla;
    private javax.swing.JTextField txtTotalKostnadAvd;
    private javax.swing.JTextField txtTotalKostnadMina;
    // End of variables declaration//GEN-END:variables
}
